# Generated by Django 5.1.4 on 2025-01-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_student_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='Aadhar Number', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Permanent Account Number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for transactions', max_length=50, null=True),
        ),
    ]
