# Generated by Django 5.1.4 on 2025-01-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_options_question_image_and_more'),
        ('users', '0007_customuser_latitude_customuser_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects taught by the teacher', related_name='teachers', to='questions.subject'),
        ),
    ]
