# Generated by Django 5.1.4 on 2025-01-28 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('ebook', 'Ebook'), ('blog', 'Blog'), ('study_material', 'Study Material')], max_length=20)),
                ('content_id', models.PositiveIntegerField(help_text='ID of the purchased content')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_content', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
