# Generated by Django 5.1.4 on 2025-01-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Mark this blog as premium.'),
        ),
        migrations.AddField(
            model_name='blog',
            name='unlock_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Unlock cost in XamCoins or Wallet Money.', max_digits=10),
        ),
    ]
