# Generated by Django 5.1.4 on 2024-12-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0002_remove_question_options_question_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the exam', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short description of the exam', null=True)),
                ('total_marks', models.PositiveIntegerField(help_text='Total marks for the exam')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the exam in minutes')),
                ('scheduled_at', models.DateTimeField(help_text='Scheduled date and time for the exam')),
                ('is_active', models.BooleanField(default=False, help_text='Status of the exam (active or not)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='questions.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the section', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the section', null=True)),
                ('marks', models.PositiveIntegerField(help_text='Total marks for the section')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='SectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField(help_text='Marks assigned to this question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_questions', to='questions.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_questions', to='exams.section')),
            ],
        ),
    ]
