# Generated by Django 5.1.4 on 2024-12-10 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_exam_created_at_remove_exam_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='exams.exam'),
        ),
    ]
