# Generated by Django 5.1.4 on 2025-01-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreadingactivity',
            name='coins_earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total XamCoins earned', max_digits=15),
        ),
        migrations.AlterField(
            model_name='xamcoinsettings',
            name='coins_per_minute',
            field=models.DecimalField(decimal_places=2, help_text='XamCoins credited per minute after this threshold', max_digits=10),
        ),
    ]
