# Generated by Django 5.1.4 on 2025-01-28 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_alter_blogreadingactivity_coins_earned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_count', models.PositiveIntegerField(default=0, help_text='Current streak count in days')),
                ('last_participation_date', models.DateField(blank=True, help_text='Date of last contest participation', null=True)),
                ('bonus_earned', models.DecimalField(decimal_places=2, default=0.0, help_text='Total bonus earned from streaks', max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contest_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
