# Generated by Django 5.1.4 on 2025-01-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_conteststreak'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestStreakReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(help_text='Day of the streak', unique=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=10.0, help_text='XamCoins rewarded for this day in the streak', max_digits=10)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
