# Generated by Django 5.1.4 on 2024-12-16 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_referralbonus_referral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'wallet_type')},
        ),
    ]
