# Generated by Django 5.1.4 on 2025-01-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_wallet_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='XamCoinConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Value of 1 XamCoin in INR', max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission percentage for XamCoin to money conversion', max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('earnexam', 'Earnexam Wallet'), ('winnings', 'Winnings Wallet'), ('discount', 'Discount Bonus Wallet'), ('xamcoins', 'XamCoins')], max_length=10),
        ),
    ]
