# Generated by Django 5.1.4 on 2025-01-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_xamcoinconversion_alter_wallet_wallet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='xamcoinconversion',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Mark this conversion rate as active'),
        ),
        migrations.AlterField(
            model_name='xamcoinconversion',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Commission percentage charged for conversions', max_digits=5),
        ),
        migrations.AlterField(
            model_name='xamcoinconversion',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, help_text='Conversion rate for XamCoins (e.g., 1 XamCoin = X INR)', max_digits=10),
        ),
    ]
