# Generated by Django 5.1.4 on 2025-01-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_xamcoinconversion_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xamcoinconversion',
            options={'verbose_name': 'XamCoin Conversion Rule', 'verbose_name_plural': 'XamCoin Conversion Rules'},
        ),
        migrations.RemoveField(
            model_name='xamcoinconversion',
            name='commission_percentage',
        ),
        migrations.AddField(
            model_name='xamcoinconversion',
            name='conversion_commission',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Commission percentage for conversion', max_digits=5),
        ),
        migrations.AlterField(
            model_name='xamcoinconversion',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, help_text='Conversion rate (e.g., 1 XamCoin = INR value)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='xamcoinconversion',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only one rule can be active at a time'),
        ),
    ]
