# Generated by Django 5.1.4 on 2025-01-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_referralbonus_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralbonus',
            name='referral_amount',
        ),
        migrations.AddField(
            model_name='referralbonus',
            name='referred_user_bonus',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='One-time bonus for referred user on signup', max_digits=10),
        ),
        migrations.AlterField(
            model_name='referralbonus',
            name='referrer_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Bonus for referrer when reaching milestone', max_digits=10),
        ),
    ]
