# Generated by Django 5.1.4 on 2024-12-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0002_remove_question_options_question_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the quiz', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short description of the quiz')),
                ('is_active', models.BooleanField(default=False, help_text='Activate or deactivate the quiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the section', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the section')),
                ('num_questions', models.PositiveIntegerField(help_text='Number of questions in the section')),
                ('total_marks', models.PositiveIntegerField(help_text='Total marks for the section')),
                ('is_active', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='SectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField(help_text='Marks assigned to this question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_section_questions', to='questions.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_questions', to='quizzes.section')),
            ],
        ),
    ]
