# Generated by Django 5.1.4 on 2024-12-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='End date and time of the quiz', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('P2P', 'Peer-to-Peer Battle'), ('MEGA', 'Mega Contest'), ('GROUP', 'Group Battle'), ('DAILY', 'Daily Quiz'), ('OLYMPIAD', 'Olympiad'), ('SELF', 'Self Challenge'), ('EXAM', 'Exam')], default='DAILY', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start date and time of the quiz', null=True),
        ),
    ]
