# Generated by Django 5.1.4 on 2024-12-16 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
        ('quizzes', '0002_quiz_end_date_quiz_quiz_type_quiz_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='quiz_type',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='total_prize',
        ),
        migrations.AddField(
            model_name='contest',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Admin commission in percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='contest',
            name='participant_limit',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of participants allowed'),
        ),
        migrations.AddField(
            model_name='contest',
            name='quiz',
            field=models.OneToOneField(help_text='Quiz associated with this contest', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='contest',
            name='winner_percentage',
            field=models.DecimalField(decimal_places=2, default=62, help_text='Percentage of winners', max_digits=5),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the contest'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(help_text='End time of the contest'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, help_text='Entry fee for the contest', max_digits=10),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(help_text='Start time of the contest'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(help_text='Title of the contest', max_length=255),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Rank of the participant', null=True)),
                ('prize', models.DecimalField(decimal_places=2, default=0.0, help_text='Prize amount won', max_digits=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Time when the user joined')),
                ('contest', models.ForeignKey(help_text='Contest this participant joined', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrizeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='Rank in the contest')),
                ('prize_amount', models.DecimalField(decimal_places=2, help_text='Prize amount for this rank', max_digits=10)),
                ('contest', models.ForeignKey(help_text='Contest associated with the prizes', on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='contests.contest')),
            ],
        ),
        migrations.DeleteModel(
            name='ContestQuestion',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
